"""ModeratorIM app SDK — the contract kernel external apps build against.

An app imports ONLY from this package (``from moderatorim.sdk import Manifest, Model, ...``); it
never imports ``moderatorim.core``. Core implements these contracts and injects live handles (the
``Ctx``) at runtime, so an app reaches core's behavior without depending on it.

``moderatorim`` is a PEP 420 namespace shared with ``moderatorim-core`` — this package owns only
``moderatorim.sdk``.
"""

from moderatorim.sdk.bus import (
    Action,
    ActionKind,
    Event,
    EventBus,
    EventKind,
    Handler,
    Subscription,
)
from moderatorim.sdk.cachestore import (
    CacheStore,
)
from moderatorim.sdk.datastore import (
    DataStore,
    Filter,
    FilterList,
    FilterOp,
    Record,
    RecordList,
    Search,
    TableAccessDenied,
)
from moderatorim.sdk.models import (
    CREATED_AT_FIELD,
    CREATED_BY_FIELD,
    ID_FIELD,
    INHERIT_ONLY_FACETS,
    OVERRIDABLE_FACETS,
    SOFT_DELETE_FIELD,
    UPDATED_AT_FIELD,
    UPDATED_BY_FIELD,
    Extends,
    FieldChoice,
    FieldType,
    ResolvedColumn,
    ResolvedSchema,
    TableColumn,
    TableModel,
    assert_valid_override,
    choice,
    listref,
    ref,
    text,
)
from moderatorim.sdk.registry import (
    AuthMethod,
    Manifest,
    NavEntry,
    UnitType,
)
from moderatorim.sdk.validation import (
    Email,
    Max,
    MaxLength,
    Min,
    MinLength,
    OneOf,
    PasswordPolicy,
    Pattern,
    Required,
    Result,
    ValidationError,
    Validator,
    build_validators,
    validate_field,
    validate_form,
)
from moderatorim.sdk.views import (
    BarChart,
    CalendarView,
    DashboardView,
    Field,
    FormAction,
    FormFields,
    FormList,
    FormOverview,
    FormSave,
    FormTab,
    FormView,
    ListCard,
    ListCardAction,
    ListCardField,
    ListView,
    MetricSource,
    ModalAction,
    ModalView,
    PageRoute,
    PageView,
    Permission,
    PermissionAction,
    Route,
    RouteMethod,
    ScoreBand,
    ScoreCard,
    SeriesSource,
    StatCard,
    StatusBadge,
    ViewExtension,
    ViewModel,
    ViewRoute,
)
from moderatorim.sdk.web import (
    App,
    Ctx,
    Fragment,
    Kind,
    Page,
    Redirect,
    Rendered,
    RouteDef,
    redirect,
)

__all__ = [
    # models
    "TableModel",
    "TableColumn",
    "FieldType",
    "Extends",
    "ResolvedColumn",
    "ResolvedSchema",
    "ID_FIELD",
    "SOFT_DELETE_FIELD",
    "CREATED_AT_FIELD",
    "CREATED_BY_FIELD",
    "UPDATED_AT_FIELD",
    "UPDATED_BY_FIELD",
    "ref",
    "choice",
    "FieldChoice",
    "assert_valid_override",
    "OVERRIDABLE_FACETS",
    "INHERIT_ONLY_FACETS",
    "listref",
    "text",
    # datastore port
    "DataStore",
    "Filter",
    "FilterList",
    "FilterOp",
    "Record",
    "RecordList",
    "Search",
    "TableAccessDenied",
    # cachestore port
    "CacheStore",
    # bus
    "Event",
    "EventKind",
    "Action",
    "ActionKind",
    "EventBus",
    "Subscription",
    "Handler",
    # manifest
    "Manifest",
    "UnitType",
    "NavEntry",
    "AuthMethod",
    # views (declarative model-driven view descriptors)
    "Field",
    "ListView",
    "PageView",
    "PageRoute",
    "Permission",
    "PermissionAction",
    "Route",
    "RouteMethod",
    "ViewModel",
    "CalendarView",
    "BarChart",
    "DashboardView",
    "MetricSource",
    "ScoreBand",
    "ScoreCard",
    "SeriesSource",
    "StatCard",
    "ViewRoute",
    "FormSave",
    "FormView",
    "ModalAction",
    "ModalView",
    "FormTab",
    "FormFields",
    "FormList",
    "ListCard",
    "ListCardAction",
    "ListCardField",
    "FormOverview",
    "FormAction",
    "StatusBadge",
    "ViewExtension",
    # validation (declare-once: render HTML hints + enforce server-side)
    "Validator",
    "Required",
    "MinLength",
    "MaxLength",
    "Min",
    "Max",
    "Pattern",
    "Email",
    "OneOf",
    "PasswordPolicy",
    "ValidationError",
    "Result",
    "validate_field",
    "validate_form",
    "build_validators",
    # web facade (dispatch adapter lives in core)
    "App",
    "Ctx",
    "Page",
    "Fragment",
    "Rendered",
    "Redirect",
    "redirect",
    "RouteDef",
    "Kind",
]
