"""The model-driven view descriptors domain (declarative; core renders them)."""

from moderatorim.sdk.views.descriptors import (
    CalendarView,
    Field,
    FormAction,
    FormFields,
    FormList,
    FormOverview,
    FormSave,
    FormTab,
    FormView,
    ListView,
    ModalAction,
    ModalView,
    PageRoute,
    PageView,
    Permission,
    PermissionAction,
    Route,
    RouteMethod,
    ViewExtension,
    ViewModel,
    ViewRoute,
)

__all__ = [
    "CalendarView",
    "Field",
    "FormAction",
    "FormFields",
    "FormList",
    "FormOverview",
    "FormTab",
    "FormSave",
    "FormView",
    "ModalAction",
    "ModalView",
    "ListView",
    "PageView",
    "PageRoute",
    "Permission",
    "PermissionAction",
    "Route",
    "RouteMethod",
    "ViewExtension",
    "ViewModel",
    "ViewRoute",
]
